import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Image from "next/image";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Image
                    className="background-image"
                    src={"/background.avif"}
                    alt=""
                    width={500}
                    height={400}
                ></Image>
                <Header></Header>
                <ToastContainer></ToastContainer>
                {children}
            </body>
        </html>
    );
}
